hw1
Mur0riki/tinkoff-java-2024 pull request #1
Opened 2024-02-09 12:23 UTC by Mur0riki

2024-02-15 10:42 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandHelp.java
> +        listCommand.forEach(command ->
Я сделал бы это немного по-другому:

```java
        listCommand.stream()
                   .map(command -> STRING_COMMANDS_ENUMERATION.formatted(command.command(), command.description()))
                   .forEach(commandListString::append)
```

2024-02-15 10:51 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandList.java
> +        if (userOptional.isPresent()) {
Не совсем корректно так использовать `Optional`, ведь одно из его преимуществ в том, что можно не делать проверку на `null`. Попробуй поиграться с `.map()` и `.flatMap()`

2024-02-15 10:56 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandList.java
> +        sitesString.append(USER_TRACK_SITES_MESSAGE.formatted(uriList.size()));
Попробуй сделать через Stream API

2024-02-15 10:56 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandStart.java
> +        if (userOptional.isEmpty()) {
Тоже самое что и выше, через `Optional`...

2024-02-15 10:56 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandTrack.java
> +        if (userOptional.isPresent()) {
И тут

2024-02-15 10:57 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/controller/MessageController.java
> +    public int process(List<Update> list) {
Желательно вынести в отдельные приватные методы для большей читабельности

2024-02-18 19:34 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandList.java
> +        var userOptional = userService.findUserById(chatId);
Не совсем правильно используется `Optional`

2024-02-18 19:35 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandList.java
> +    private String prepareListSitesMessage(List<URI> uriList) {
Можно сделать красивее: переменная не нужна, в конструктор `StringBuilder` можно передать USER_TRACK_SITES_MESSAGE, а не через `.append()`

2024-02-18 19:36 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandStart.java
> +        return (String) userOptional.map(u -> ALREADY_REGISTRATE_MESSAGE)
Так же неправильное использование `Optional`:

```java
        return userService.findUserById(chatId)
                          .map(u -> ALREADY_REGISTRATE_MESSAGE)
                          .orElseGet(() -> {
                              userService.saveUser(new User(chatId, List.of(), SessionState.BASE_STATE));

                              return SUCCESS_REGISTRATION_MESSAGE;
                          });
```

2024-02-18 19:39 UTC, CbaKKa requested changes
Привет, у меня сложилось впечатление, что ты не до конца понимаешь как работает `Optional` и для чего он нужен, можем созвониться, либо самостоятельно изучи этот вопрос, ответь, пожалуйста, до вечера 20.02

2024-02-19 11:46 UTC, Mur0riki commented
Я бы хотел как изучить самостоятельно, так и созвониться после самостоятельного изучения для понимания того насколько я правильно понял Optional и для чего он нужен.

2024-02-19 12:00 UTC, CbaKKa commented
Тогда напиши мне в тг @max_zhurov, созвонимся как будешь готов

2024-02-21 13:51 UTC, CbaKKa requested changes
В целом, все отлично, пару мелочей поправить надо

2024-02-21 13:51 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandTrack.java
> +    @Override
Нужно навесить `@Transactional` т.к. нужно обеспечить консистентность данных (пока читаем и ставим `state` что-то может измениться)

2024-02-21 13:51 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandTrack.java
> +                changeStatusUserAndSave(userService.findUserById(chatId).get());
Надо переделать на что-то такое: `userService.findUserById(chatId).ifPresent(this::changeStatusUserAndSave)`

2024-02-21 13:51 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandUntrack.java
> +                changeStatusUserAndSave(userService.findUserById(chatId).get());
Тут тоже надо `ifPresent`

2024-02-21 13:51 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/service/MessageService.java
> +    public static final String INVALID_URI_MESSAGE = "Неверно указан URI.";
Лучше удалять неиспользуемые переменные, потом, если что, добавить заново

2024-02-21 13:51 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/service/MessageService.java
> +                return processStateUserMessage(userRepository.findUserById(chatId).get(), new URI(text));
Переделать на `ifPresent`

2024-02-21 14:11 UTC, Mur0riki commented on bot/src/main/java/edu/java/bot/commands/CommandTrack.java
> +                changeStatusUserAndSave(userService.findUserById(chatId).get());
Мне кажется тут более удобно будет использовать Supplier нежели Consumer потому что мне нужно возвращать String исходя из того найден пользователь в бд или нет

2024-02-21 14:14 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandTrack.java
> +                changeStatusUserAndSave(userService.findUserById(chatId).get());
Если код дошел до этого места - то он 100% найден.
Вообще, повторный вызов репозитория здесь не нужен

2024-02-21 14:16 UTC, CbaKKa requested changes

2024-02-21 14:16 UTC, CbaKKa commented on bot/src/main/java/edu/java/bot/commands/CommandTrack.java
> +                changeStatusUserAndSave(userService.findUserById(chatId).get());
Имеет смысл добавить `.map(User::getId).map(...)` и внутри второго мапа уже вызывать этот приватный метод

2024-02-26 16:46 UTC, merged